/**
 * Stage 4 — Dual Image Generation (No Video)
 * Ref: 13_CONTENT_OPS_PIPELINE §6.3.5
 *
 * NON-NEGOTIABLE: Any video request → failed with reason video_not_allowed.
 * Status: remains 'qa'.
 *
 * Generates TWO images per post:
 *   1. featured_image — for WordPress featured_media
 *   2. hero_image — for in-content hero block
 *
 * Wait/Queue mechanism:
 *   - Bounded retries with exponential backoff (1s, 2s, 4s, 8s, 16s cap)
 *   - max_attempts: 8
 *   - hard_timeout: 60s per image
 *   - Clear logging: image_role, attempt, status
 *
 * Both images MUST succeed or stage fails closed (imageRequired=true).
 * If imageRequired=false and generation fails → continue without images.
 */

import { SCHEMA_VERSION } from '../types';
import type { Stage3Output, Stage4Output, ImageAsset } from '../types';
import type { PublishQueueRepo } from '../db/repositories';
import type { WriterService } from '../services/writer';
import { logger } from '../logger';

// ─── Default Retry Constants ────────────────────────────────────
const DEFAULT_MAX_ATTEMPTS = 8;
const DEFAULT_BASE_BACKOFF_MS = 1000;
const DEFAULT_BACKOFF_CAP_MS = 16000;
const DEFAULT_HARD_TIMEOUT_MS = 60_000;
const DEFAULT_WIDTH = 1200;
const DEFAULT_HEIGHT = 630;

export type ImageRole = 'featured' | 'hero';

export interface RetryConfig {
  maxAttempts?: number;
  baseBackoffMs?: number;
  backoffCapMs?: number;
  hardTimeoutMs?: number;
}

export interface Stage4Input {
  queueId: string;
  runId?: string;
  stage3: Stage3Output;
  queueRepo: PublishQueueRepo;
  imageRequired: boolean;
  writerService?: WriterService;
  /** Override retry defaults for testing. Production uses safe defaults. */
  retryConfig?: RetryConfig;
}

export interface Stage4Result {
  ok: boolean;
  output?: Stage4Output;
  failReason?: string;
}

/**
 * Detect video requests in content or prompts.
 * Any mention of video → fail with video_not_allowed.
 */
function detectVideoRequest(stage3: Stage3Output): boolean {
  const searchText = [
    stage3.content_markdown,
    stage3.featured_image?.prompt || '',
    stage3.title,
  ]
    .join(' ')
    .toLowerCase();

  const videoPatterns = [
    'video',
    'youtube embed',
    'vimeo',
    'mp4',
    'webm',
    'video player',
    'video embed',
  ];

  // Only flag if it's clearly a request for video content/embed, not just a mention
  return videoPatterns.some(
    (p) =>
      searchText.includes(`generate ${p}`) ||
      searchText.includes(`create ${p}`) ||
      searchText.includes(`embed ${p}`) ||
      searchText.includes(`include ${p}`)
  );
}

/**
 * Sleep for the given duration.
 */
function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

/**
 * Calculate backoff delay: baseMs * 2^(attempt-1), capped.
 */
function getBackoffMs(attempt: number, baseMs: number, capMs: number): number {
  const delay = baseMs * Math.pow(2, attempt - 1);
  return Math.min(delay, capMs);
}

/**
 * Wrap a single image generation call with bounded retries + hard timeout.
 *
 * Logs: image_role, attempt, status (queued|generating|ready|failed|timeout)
 *
 * Returns the generated bytes or null if all attempts exhausted.
 */
async function generateImageWithRetry(
  writerService: WriterService,
  prompt: string,
  altText: string,
  role: ImageRole,
  queueId: string,
  retryConfig?: RetryConfig
): Promise<{
  image_base64: string;
  mime_type: string;
  alt_text: string;
} | null> {
  const maxAttempts = retryConfig?.maxAttempts ?? DEFAULT_MAX_ATTEMPTS;
  const baseBackoffMs = retryConfig?.baseBackoffMs ?? DEFAULT_BASE_BACKOFF_MS;
  const backoffCapMs = retryConfig?.backoffCapMs ?? DEFAULT_BACKOFF_CAP_MS;
  const hardTimeoutMs = retryConfig?.hardTimeoutMs ?? DEFAULT_HARD_TIMEOUT_MS;

  for (let attempt = 1; attempt <= maxAttempts; attempt++) {
    logger.info('Stage 4: image generation attempt', {
      image_role: role,
      attempt,
      status: 'generating',
      queue_id: queueId,
    });

    try {
      // Hard timeout via Promise.race
      const timeoutPromise = new Promise<never>((_, reject) =>
        setTimeout(() => reject(new Error('hard_timeout')), hardTimeoutMs)
      );

      const genPromise = writerService.generateImageBytes(prompt, altText);

      const result = await Promise.race([genPromise, timeoutPromise]);

      logger.info('Stage 4: image generation succeeded', {
        image_role: role,
        attempt,
        status: 'ready',
        queue_id: queueId,
        mime_type: result.mime_type,
      });

      return result;
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      const isTimeout = msg === 'hard_timeout';

      logger.warn('Stage 4: image generation attempt failed', {
        image_role: role,
        attempt,
        status: isTimeout ? 'timeout' : 'failed',
        queue_id: queueId,
        error: msg.slice(0, 200),
      });

      // If we have more attempts, wait with backoff
      if (attempt < maxAttempts) {
        const backoff = getBackoffMs(attempt, baseBackoffMs, backoffCapMs);
        logger.info('Stage 4: waiting before retry', {
          image_role: role,
          attempt,
          backoff_ms: backoff,
          status: 'queued',
          queue_id: queueId,
        });
        await sleep(backoff);
      }
    }
  }

  // All attempts exhausted
  logger.error('Stage 4: image generation exhausted all attempts', {
    image_role: role,
    max_attempts: maxAttempts,
    status: 'failed',
    queue_id: queueId,
  });

  return null;
}

/**
 * Build an image prompt tailored for a specific role.
 * LOCKED: image_only mode — no video, no animation, no GIF.
 */
function buildRolePrompt(
  basePrompt: string,
  role: ImageRole,
  keyword: string,
  title: string
): string {
  if (role === 'hero') {
    return [
      `Wide cinematic hero banner image (image_only, NO video, NO animation, NO GIF):`,
      `${basePrompt}.`,
      `Title: "${title}". Keyword: ${keyword}.`,
      `Aspect ratio 16:9, vibrant golf photography, shallow depth of field,`,
      `soft natural lighting, editorial quality. Static image only.`,
    ].join(' ');
  }
  // Featured: square-ish thumbnail
  return basePrompt;
}

export async function runStage4(input: Stage4Input): Promise<Stage4Result> {
  const { queueId, stage3, queueRepo, imageRequired, writerService } = input;

  // NON-NEGOTIABLE: No video (§6.3.5)
  if (detectVideoRequest(stage3)) {
    logger.error('Stage 4: VIDEO REQUEST REJECTED', { queue_id: queueId });
    queueRepo.updateStatus(queueId, 'failed', {
      fail_reasons: JSON.stringify(['video_not_allowed']),
    });
    return { ok: false, failReason: 'video_not_allowed' };
  }

  // Build image plan — use LLM if writerService available
  let featuredImagePlan = stage3.featured_image;

  if (writerService) {
    try {
      const generated = await writerService.generateImage(
        stage3.focus_keyword,
        stage3.title
      );
      featuredImagePlan = {
        prompt: generated.prompt || featuredImagePlan?.prompt || `Golf illustration for ${stage3.focus_keyword}`,
        alt_text: generated.alt_text || featuredImagePlan?.alt_text || stage3.focus_keyword,
      };
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      logger.warn('Stage 4: image prompt generation failed, using stage3 prompts', { error: msg });
    }
  }

  if (!featuredImagePlan || !featuredImagePlan.alt_text) {
    if (imageRequired) {
      queueRepo.updateStatus(queueId, 'hold', {
        fail_reasons: JSON.stringify(['missing_alt_text']),
      });
      return { ok: false, failReason: 'missing_alt_text' };
    }
  }

  // ── Dual Image Generation ──────────────────────────────────────
  // Generate both featured and hero images with bounded retries.
  // Both must succeed when imageRequired=true.
  let featuredAsset: ImageAsset | null = null;
  let heroAsset: ImageAsset | null = null;
  let imageResult: Stage4Output['image_result'] = null;

  if (writerService) {
    const basePrompt =
      featuredImagePlan?.prompt || `Golf illustration for ${stage3.focus_keyword}`;
    const baseAltText =
      featuredImagePlan?.alt_text || stage3.focus_keyword;

    // ── Generate Featured Image ──────────────────────────────────
    const featuredPrompt = buildRolePrompt(basePrompt, 'featured', stage3.focus_keyword, stage3.title);
    const featuredResult = await generateImageWithRetry(
      writerService,
      featuredPrompt,
      baseAltText,
      'featured',
      queueId,
      input.retryConfig
    );

    if (featuredResult) {
      featuredAsset = {
        prompt_used: featuredPrompt,
        image_base64: featuredResult.image_base64,
        mime: featuredResult.mime_type,
        width: DEFAULT_WIDTH,
        height: DEFAULT_HEIGHT,
        alt_text: featuredResult.alt_text,
      };
      // Backward compat: populate image_result
      imageResult = {
        image_base64: featuredResult.image_base64,
        mime_type: featuredResult.mime_type,
        alt_text: featuredResult.alt_text,
      };
    }

    // ── Generate Hero Image ──────────────────────────────────────
    const heroPrompt = buildRolePrompt(basePrompt, 'hero', stage3.focus_keyword, stage3.title);
    const heroAltText = `${baseAltText} - hero`;
    const heroResult = await generateImageWithRetry(
      writerService,
      heroPrompt,
      heroAltText,
      'hero',
      queueId,
      input.retryConfig
    );

    if (heroResult) {
      heroAsset = {
        prompt_used: heroPrompt,
        image_base64: heroResult.image_base64,
        mime: heroResult.mime_type,
        width: DEFAULT_WIDTH,
        height: DEFAULT_HEIGHT / 2, // 16:9 hero aspect
        alt_text: heroResult.alt_text,
      };
    }

    // ── Fail-closed: both MUST succeed if imageRequired=true ─────
    if (imageRequired) {
      if (!featuredAsset && !heroAsset) {
        queueRepo.updateStatus(queueId, 'hold', {
          fail_reasons: JSON.stringify(['image_generation_failed']),
        });
        return { ok: false, failReason: 'image_generation_failed' };
      }
      if (!featuredAsset) {
        queueRepo.updateStatus(queueId, 'failed', {
          fail_reasons: JSON.stringify(['featured_image_generation_failed']),
        });
        return { ok: false, failReason: 'featured_image_generation_failed' };
      }
      if (!heroAsset) {
        queueRepo.updateStatus(queueId, 'failed', {
          fail_reasons: JSON.stringify(['hero_image_generation_failed']),
        });
        return { ok: false, failReason: 'hero_image_generation_failed' };
      }
    }

    logger.info('Stage 4: dual image generation complete', {
      queue_id: queueId,
      featured_ready: featuredAsset ? 'yes' : 'no',
      hero_ready: heroAsset ? 'yes' : 'no',
    });
  }

  const output: Stage4Output = {
    schema_version: SCHEMA_VERSION,
    featured_image: {
      prompt: featuredImagePlan?.prompt || `Golf illustration for ${stage3.focus_keyword}`,
      alt_text: featuredImagePlan?.alt_text || stage3.focus_keyword,
    },
    inline_image: null,
    media_mode: 'image_only',
    image_result: imageResult,
    images: {
      featured: featuredAsset,
      hero: heroAsset,
    },
  };

  logger.info('Stage 4: image plan complete', {
    queue_id: queueId,
    has_featured_image: featuredAsset ? 'yes' : 'no',
    has_hero_image: heroAsset ? 'yes' : 'no',
    has_image_bytes: imageResult ? 'yes' : 'no',
  });

  return { ok: true, output };
}
